# Generated by Django 5.2.13 on 2026-04-30 10:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_id', models.CharField(max_length=200, unique=True)),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_timezone', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['agency_name'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monday', models.CharField(max_length=1)),
                ('tuesday', models.CharField(max_length=1)),
                ('wednesday', models.CharField(max_length=1)),
                ('thursday', models.CharField(max_length=1)),
                ('friday', models.CharField(max_length=1)),
                ('saturday', models.CharField(max_length=1)),
                ('sunday', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['service_id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('exception_type', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['service_id'],
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=200)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.PositiveIntegerField()),
                ('shape_dist_traveled', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['shape_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_id', models.CharField(max_length=200)),
                ('route_type', models.IntegerField()),
                ('route_short_name', models.CharField(max_length=200, null=True)),
                ('route_long_name', models.CharField(max_length=500, null=True)),
                ('route_color', models.CharField(max_length=6, null=True)),
                ('route_text_color', models.CharField(max_length=6, null=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.agency')),
            ],
            options={
                'ordering': ['agency', 'route_short_name', 'route_long_name'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_id', models.CharField(max_length=200)),
                ('stop_name', models.CharField(max_length=500, null=True)),
                ('stop_lat', models.FloatField(null=True)),
                ('stop_lon', models.FloatField(null=True)),
                ('location_type', models.CharField(max_length=1, null=True)),
                ('parent_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.stop')),
            ],
            options={
                'ordering': ['stop_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=200)),
                ('service_id', models.CharField(max_length=200)),
                ('direction_id', models.CharField(max_length=1, null=True)),
                ('shape', models.CharField(max_length=200, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.route')),
            ],
            options={
                'ordering': ['trip_id'],
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_sequence', models.PositiveIntegerField()),
                ('arrival_time', models.CharField(max_length=8, null=True)),
                ('departure_time', models.CharField(max_length=8, null=True)),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.trip')),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
            },
        ),
    ]
