# Generated by Django 5.2.13 on 2026-05-02 07:53

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password

def create_user(apps, _):
    User = apps.get_model('data_management', 'User')

    username = 'admin'
    email = 'admin@admin.com'
    password = 'AdminHeslo'

    user = User.objects.filter(username = username).first()

    if not user:
        User.objects.create(
            username = username,
            email = email,
            password = make_password(password),
            is_active = True,
            is_staff = False,
            is_superuser = False
        )
        print(' Používateľ bol vytvorený.')
    else:
        user.email = email
        user.password = make_password(password)
        user.save()
        print(' Používateľ bol aktualizovaný.')

class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
